[tool.poetry]
name = "neural-semigroups"
version = "0.3.1"
description = "Neural networks powered research of semigroups"
authors = ["Boris Shminke <boris@shminke.ml>"]
license = "Apache-2.0"
repository = "https://github.com/inpefess/neural-semigroups"
documentation = "https://neural-semigroups.readthedocs.io"
readme = "README.md"
classifiers=[
	"Programming Language :: Python :: 3.6",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
	"Intended Audience :: Science/Research",
	"Development Status :: 3 - Alpha",
	"Environment :: Console",
	"Natural Language :: English",
	"Topic :: Scientific/Engineering :: Artificial Intelligence",
	"Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6.1"
torch = "*"
tqdm = "*"
pandas = "*"
pytorch-ignite = "*"
tensorboard = "*"

[tool.poetry.dev-dependencies]
torch = "1.5.0"
tqdm = "4.45.0"
pandas = "1.0.3"
pytorch-ignite = "0.3.0"
tensorboard = "2.2.0"
pycodestyle = "2.5.0"
pylint = "2.4.4"
mypy = "0.770"
rope = "0.16.0"
flake8 = "3.7.9"
autopep8 = "1.5.1"
black = "19.10b0"
virtualenv = "20.0.17"
yapf = "0.29.0"
matplotlib = "3.2.1"
seaborn = "0.10.0"
pytest = "5.4.1"
sphinx = "2.4.4"
sphinx_rtd_theme = "0.4.3"
pytest-cov = "2.8.1"
sphinx-autodoc-typehints = "1.10.3"
scikit-learn = "0.22.2.post1"
pre-commit = "2.3.0"
jupyterlab = "2.1.2"

[tool.black]
line-length=79
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

