[tool.poetry]
name = "neural-semigroups"
version = "0.5.4"
description = "Neural networks powered research of semigroups"
authors = ["Boris Shminke <boris@shminke.ml>"]
license = "Apache-2.0"
repository = "https://github.com/inpefess/neural-semigroups"
documentation = "https://neural-semigroups.readthedocs.io"
readme = "README.md"
classifiers=[
	"Programming Language :: Python :: 3.6",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
	"Intended Audience :: Science/Research",
	"Development Status :: 3 - Alpha",
	"Environment :: Console",
	"Natural Language :: English",
	"Topic :: Scientific/Engineering :: Artificial Intelligence",
	"Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6.1"
torch = "*"
tqdm = "*"
pytorch-ignite = "*"
tensorboard = "*"

[tool.poetry.dev-dependencies]
torch = {url = "https://download.pytorch.org/whl/cu110/torch-1.7.0%2Bcu110-cp36-cp36m-linux_x86_64.whl"}
pylint = "*"
mypy = "*"
rope = "*"
flake8 = "*"
virtualenv = "*"
pytest = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
pytest-cov = "*"
sphinx-autodoc-typehints = "*"
scikit-learn = "*"
pre-commit = "*"
jupyterlab = "*"
ipywidgets = "*"
black = "^19.10b0"
data-science-types = "*"
vulture = "*"
kaggle = "*"
matplotlib = "*"

[tool.black]
line-length=79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
src_paths = ["neural_semigroups"]
